r20_esc:
  outputs:
    silver:
      type: athena
      database: awsdatacatalog
      schema: glue_reg20_silver
      s3_staging_dir: "{{ env_var('ATHENA_RESULTS_BUCKET') }}"
      s3_data_dir: "{{ env_var('SILVER_BUCKET') }}"
      region_name: us-east-1
      threads: 1
      num_retries: 5

    redshift_gold:
      type: redshift
      method: iam
      host: "{{ env_var('REDSHIFT_HOST') }}"
      port: "{{ env_var('REDSHIFT_PORT') | int }}"
      database: "{{ env_var('REDSHIFT_DB') }}"
      schema: "{{ env_var('REDSHIFT_SCHEMA') }}"
      user: "{{ env_var('REDSHIFT_USER') }}"
      cluster_id: "{{ env_var('REDSHIFT_WORKGROUP_NAME') }}"
      region: "{{ env_var('AWS_REGION') }}"
      threads: 4

  target: silver
