[tools]
trufflehog = "latest"
terraform = "1.11.3"
pre-commit = "latest"

[tasks.setup]
description = "Install pre-commit hooks"
run = "pre-commit install"

[tasks.trufflehog-scan]
run = "trufflehog git file://. --since-commit HEAD --no-verification --fail"
description = "Scan for secrets"
