name: General checks and tests (no credentials required)
on:
  workflow_call:
    inputs:
      path:
        type: string
        default: "."

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  yaml_lint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        id: checkout
      # yamllint version here should match the one in .pre-commit-config.yaml for consistency
      - name: Run Yamllint
        run: |
          # Install yamllint
          pip install --user yamllint==1.35.1
          # Run yamllint
          yamllint --strict --config-file .config/.yamllint.yaml ${{ inputs.path }}

  gitleaks:
    name: Detect Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      # There is a Gitleaks action provided by the developers but it requires a license for organizations
      - name: Install and Run Gitleaks
        run: |
          GITLEAKS_VERSION=$(curl -s "https://api.github.com/repos/gitleaks/gitleaks/releases/latest" | jq '.tag_name' | sed 's/"//g')
          wget -qO gitleaks.tar.gz https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_$GITLEAKS_VERSION_$(uname).tar.gz
          sudo tar xf gitleaks.tar.gz -C /usr/local/bin gitleaks
          gitleaks dir --redact --verbose
