name: terraform checks and tests (no credentials required)
on:
  workflow_call:
    inputs:
      aws_region:
        description: 'The AWS region to use for the Terraform code'
        type: string
      path:
        description: 'The relative path to the Terraform code to check'
        type: string
        default: "."
      tf_version:
        description: 'The version of Terraform to use'
        default: '1.11.3'
        type: string

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  terraform_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        id: checkout
        name: Checkout source code
      - uses: hashicorp/setup-terraform@v3
        id: setup-terraform
        name: Setup Terraform
        with:
          terraform_version: ${{ inputs.tf_version }}
      - name: fmt
        run: terraform fmt -check -recursive ${{ inputs.path }}
      - name: terraform validate
        run: |
          cd ${{ inputs.path }}
          terraform init -upgrade -input=false -lock=false -reconfigure -backend=false
          terraform validate -no-color 2>&1
      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          tflint_version: v0.52.0
      - name: Show version
        run: tflint --version
      - name: Init TFLint
        run: tflint --init --config "$(pwd)/.config/.tflint.hcl"
      - name: Run TFLint
        run: tflint --config "$(pwd)/.config/.tflint.hcl" --recursive

  terraform_security_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{ inputs.path }}
          config_file: .config/.checkov.yaml
          download_external_modules: false
          skip_path: .terraform,.terraform.lock.hcl
